<a href="https://colab.research.google.com/github/LavanyaMano/TF_learn/blob/master/Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf


In [0]:
#creating constant

number = tf.constant(10)
hello = tf.constant('hello ')

In [0]:
#creating variable

name = tf.Variable(5)
world = tf.Variable('world')

In [60]:
new_value = tf.add(name, number)


print(new_value)

Tensor("Add_8:0", shape=(), dtype=int32)


In [88]:
value_update = tf.assign(name, new_value)
print(value_update)

helloworld = tf.add(hello,world)


Tensor("Assign_5:0", shape=(), dtype=int32_ref)


In [0]:
#initializing variable without this line variable cannot be printed
init_variable = tf.global_variables_initializer()

In [0]:
sess = tf.Session()

In [86]:
sess.run(init_variable)
print(sess.run(name))

print(sess.run(new_value))

print(sess.run(value_update))

helloworld = tf.add(hello,world)

print(sess.run(helloworld))

5
15
15
b'hello world'


In [0]:
#creating placeholder

something = tf.placeholder(tf.float32)

op = 2 * something

In [42]:
# feeding value to the placeholder

result = sess.run(op, feed_dict={something:3})

print(result)

#another way

result_next = sess.run(op, {something:5})
print(result_next)

#feeding vector value

result_vector = sess.run(op, feed_dict={something:[2,4,6]})
print(result_vector)

#feed tensor/matrix

result_matrix = sess.run(op,feed_dict= {something:[[1,2,3],[3,4,5],[7,5,6]]})
print (result_matrix)



6.0
10.0
[ 4.  8. 12.]
[[ 2.  4.  6.]
 [ 6.  8. 10.]
 [14. 10. 12.]]


In [0]:
#closing session
sess.close()

In [93]:
#another way of running session.
# in this session will get executed within this block.

with tf.Session() as sess:
  
  result = sess.run(hello)
  print(result)

b'hello '
